var annotated_dup =
[
    [ "SFB", "namespaceSFB.html", [
      [ "ExtensionFilter", "structSFB_1_1ExtensionFilter.html", "structSFB_1_1ExtensionFilter" ],
      [ "IStandaloneFileBrowser", "interfaceSFB_1_1IStandaloneFileBrowser.html", "interfaceSFB_1_1IStandaloneFileBrowser" ],
      [ "StandaloneFileBrowser", "classSFB_1_1StandaloneFileBrowser.html", null ]
    ] ],
    [ "SimpleFileBrowser", "namespaceSimpleFileBrowser.html", [
      [ "EventSystemHandler", "classSimpleFileBrowser_1_1EventSystemHandler.html", null ],
      [ "FileBrowser", "classSimpleFileBrowser_1_1FileBrowser.html", "classSimpleFileBrowser_1_1FileBrowser" ],
      [ "FileBrowserAccessRestrictedPanel", "classSimpleFileBrowser_1_1FileBrowserAccessRestrictedPanel.html", null ],
      [ "FileBrowserContextMenu", "classSimpleFileBrowser_1_1FileBrowserContextMenu.html", null ],
      [ "FileBrowserCursorHandler", "classSimpleFileBrowser_1_1FileBrowserCursorHandler.html", null ],
      [ "FileBrowserFileOperationConfirmationPanel", "classSimpleFileBrowser_1_1FileBrowserFileOperationConfirmationPanel.html", "classSimpleFileBrowser_1_1FileBrowserFileOperationConfirmationPanel" ],
      [ "FileBrowserItem", "classSimpleFileBrowser_1_1FileBrowserItem.html", "classSimpleFileBrowser_1_1FileBrowserItem" ],
      [ "FileBrowserMovement", "classSimpleFileBrowser_1_1FileBrowserMovement.html", "classSimpleFileBrowser_1_1FileBrowserMovement" ],
      [ "FileBrowserQuickLink", "classSimpleFileBrowser_1_1FileBrowserQuickLink.html", "classSimpleFileBrowser_1_1FileBrowserQuickLink" ],
      [ "FileBrowserRenamedItem", "classSimpleFileBrowser_1_1FileBrowserRenamedItem.html", "classSimpleFileBrowser_1_1FileBrowserRenamedItem" ],
      [ "FileSystemEntry", "structSimpleFileBrowser_1_1FileSystemEntry.html", "structSimpleFileBrowser_1_1FileSystemEntry" ],
      [ "FiletypeIcon", "structSimpleFileBrowser_1_1FiletypeIcon.html", "structSimpleFileBrowser_1_1FiletypeIcon" ],
      [ "IListViewAdapter", "interfaceSimpleFileBrowser_1_1IListViewAdapter.html", "interfaceSimpleFileBrowser_1_1IListViewAdapter" ],
      [ "ListItem", "classSimpleFileBrowser_1_1ListItem.html", "classSimpleFileBrowser_1_1ListItem" ],
      [ "NonDrawingGraphic", "classSimpleFileBrowser_1_1NonDrawingGraphic.html", "classSimpleFileBrowser_1_1NonDrawingGraphic" ],
      [ "RecycledListView", "classSimpleFileBrowser_1_1RecycledListView.html", "classSimpleFileBrowser_1_1RecycledListView" ],
      [ "UISkin", "classSimpleFileBrowser_1_1UISkin.html", "classSimpleFileBrowser_1_1UISkin" ]
    ] ],
    [ "BasicSample", "classBasicSample.html", "classBasicSample" ],
    [ "CanvasSampleOpenFileImage", "classCanvasSampleOpenFileImage.html", "classCanvasSampleOpenFileImage" ],
    [ "CanvasSampleOpenFileText", "classCanvasSampleOpenFileText.html", "classCanvasSampleOpenFileText" ],
    [ "CanvasSampleOpenFileTextMultiple", "classCanvasSampleOpenFileTextMultiple.html", "classCanvasSampleOpenFileTextMultiple" ],
    [ "CanvasSampleSaveFileImage", "classCanvasSampleSaveFileImage.html", "classCanvasSampleSaveFileImage" ],
    [ "CanvasSampleSaveFileText", "classCanvasSampleSaveFileText.html", "classCanvasSampleSaveFileText" ],
    [ "Create_Session", "classCreate__Session.html", "classCreate__Session" ],
    [ "Deck", "classDeck.html", "classDeck" ],
    [ "Display_Unit", "classDisplay__Unit.html", "classDisplay__Unit" ],
    [ "Manager", "classManager.html", "classManager" ],
    [ "MB_CreateDeckManager", "classMB__CreateDeckManager.html", "classMB__CreateDeckManager" ],
    [ "MB_DeckUSButton", "classMB__DeckUSButton.html", null ],
    [ "MB_JSonTester", "classMB__JSonTester.html", "classMB__JSonTester" ],
    [ "NI_Display_Unit", "classNI__Display__Unit.html", "classNI__Display__Unit" ],
    [ "NI_GameManager", "classNI__GameManager.html", "classNI__GameManager" ],
    [ "NI_Selection", "classNI__Selection.html", "classNI__Selection" ],
    [ "NI_SpawnSettings", "classNI__SpawnSettings.html", "classNI__SpawnSettings" ],
    [ "NI_Timer", "classNI__Timer.html", "classNI__Timer" ],
    [ "Selection", "classSelection.html", "classSelection" ],
    [ "Singleton", "classSingleton.html", "classSingleton" ],
    [ "test", "classtest.html", "classtest" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "TMPButtonInteractableColor", "classTMPButtonInteractableColor.html", null ],
    [ "USData", "classUSData.html", "classUSData" ],
    [ "USJsonFile", "classUSJsonFile.html", "classUSJsonFile" ]
];